### ISSUE TITLE
How to avoid globals in HandleFunc? 

### ISSUE THREAD

**Issue by StevenACoffman** [zevdg/2018-codemash-go#1]
I really enjoyed your workshop today. If you have the opportunity to post the solutions to the exercises we didn't get to finish in class, I would really appreciate it.

I had a slightly different approach to solving the exercises, and I was able to avoid globals until the very last exercise when I had to hoist the flags out of the main scope for the `http.HandleFunc`. This sort of bugged me, so I ended up put the handler logic into a closure, and close over the variables I wanted to use:

```
package main

import (
	"fmt"
	"math/rand"
	"time"
	"strings"
	"flag"
	"os"
	"log"
	"net/http"
	"github.com/zevdg/2018-codemash-go/labs/01/wordbank"
)

func ipsumHandler(wordbankFile string, words int, sentenceLength int) http.Handler {
	fn := func(w http.ResponseWriter, r *http.Request) {
		ipsum, err := generateIpsum(wordbankFile, words, sentenceLength)
		if err != nil {
			log.Fatal(err)
			panic(err)
		}
		fmt.Fprintf(w, ipsum)
	}
	return http.HandlerFunc(fn)
}

func main() {
	var words int
	flag.IntVar(&words, "words", 100, "an int")

	var sentenceLength int
	flag.IntVar(&sentenceLength, "sentence-length", 6, "an int")

	var wordbankFile string
	flag.StringVar(&wordbankFile, "wordbank", "nope", "File path")

	flag.Parse()

	rand.Seed(time.Now().UnixNano())

	ih := ipsumHandler(wordbankFile, words, sentenceLength)

	http.HandleFunc("/ipsum", ih)
	http.ListenAndServe(":12345", nil)
}

func generateIpsum(wordbankFile string, wordCount int, sentenceLength int) (string, error) {
	file, err := os.Open(wordbankFile)
	if err != nil {
		return "", fmt.Errorf("calculation failed: %s", err)
	}
	defer file.Close()

	wb, err := wordbank.NewWordBank(file)

	if err != nil {
		return "", fmt.Errorf("calculation failed: %s", err)
	}
	var s []string
	ipsum := make(chan string)
	go func() {
		for i := 0; i < wordCount/sentenceLength; i++ {

			ipsum <- generateSentence(wb, sentenceLength)
		}

		if wordCount%sentenceLength > 0 {
			ipsum <- generateSentence(wb, wordCount%sentenceLength)
		}
		close(ipsum)
	}()

	for elem := range ipsum {
		s = append(s, elem)
	}
	return strings.Join(s, ". ") + ".", nil
}

func generateSentence(wb *wordbank.WordBank, wordCount int) string {
	var s []string
	for i := 0; i < wordCount; i++ {
		s = append(s, wb.GetWord())
	}
	return strings.Join(s, " ")
}

```

**Comment by zevdg** [comment]
Thanks, and well done! Using closures is a great solution and I have seen it in the wild, however it isn't the most popular approach.  Lab 9 was going to be all about solving this problem.

The most common solution is to make the handler a method on an Env or Svc struct.  [This slide](https://zevdg.github.io/2018-codemash-go/#/12/4) shows the technique, and [the solution for lab 9](https://github.com/zevdg/2018-codemash-go/blob/master/labs/09/ipsum/ipsum.go) shows it in action.  I left the cli flags as globals in that solution, but they could easily have been parsed in main and passed into the `NewService` constructor.

If you want to read more on the topic, [this blog post](http://www.alexedwards.net/blog/organising-database-access) does a wonderful job comparing several different solutions.

**Comment by StevenACoffman** [comment]
Ah! Thanks, I've been doing a lot of functional programming lately, but now yours looks obviously more idiomatic in Go. Probably best to stick to procedural, imperative struct-based solutions in this language. That's an excellent blog post, by the way. Thanks for passing it on!

Since you mentioned that Elixir was on your list to learn, you might appreciate [this article comparing Elixir and Go](https://blog.codeship.com/comparing-elixir-go/). I found reading it and also flipping between [Rosetta Code](https://blog.codeship.com/comparing-elixir-go/) solutions to common problems helpful to translate between the two.

**Comment by zevdg** [comment]
Nice, I'll add those to my reading list.
